apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress
  namespace: ingress
  labels:
    app: ingress
spec:
  selector:
    matchLabels:
      app: ingress
  template:
    metadata:
      labels:
        app: ingress
    spec:
      containers:
        - name: ingress
          image: bazel/ingress:envoy_ingress_image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
