apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: greeter
  namespace: greeter
  name: greeter

---
kind: Service
apiVersion: v1
metadata:
  namespace: greeter
  name: greeter
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: greeter
  ports:
    - name: grpc
      port: 5000
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
  namespace: greeter
  labels:
    app: greeter
spec:
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
    spec:
      serviceAccountName: greeter
      containers:
        - name: greeter
          image: bazel/greeter:greeter_service_image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

